mappings:
  VELO CAFE: кафе
  PRO MUAY THAI: кружки (музыка, муайтай, тайский, зал)
  VILLA MARKET-HUA HIN: продукты
  MS. SUPHASITA BOONTHERNG PROMPTPAY TOP UP / G-WALLET K PLUS WALLET: кружки (музыка, муайтай, тайский, зал)
  MR. CHOKCHAI SUEASUAI: other
  MRS. TANAPORN SARIGA: other
  MS. NAREERAT BUMRUNGCHU: other
  MS. WEN WEN: дом
  MRS. KSENIIA BOBKOVA: MRS. KSENIIA BOBKOVA
  MS. SUPHASITA BOONTHERNG (PROMPTPAY TOP UP / G-WALLET): кружки (музыка, муайтай, тайский, зал)
  MR. CHOKCHAI SUEASUAI PROMPTPAY TOP UP / G-WALLET K PLUS WALLET: other
  MS. OLESIA SUTYRINA: кафе
  PURCHASE E-CHN: other
  MCD-00227PTT WANGMANAO (D: other
  PTTST.D THANACHOTECHAI: бензин + мойка
  ARTIS COFFEE (THAILAND) LTD.: кафе
  MF CAFE AND RESTAURANT CO., LTD.: кафе
  LET'S RELAX-RADISSON BLU: красота
  ESC THAI WAKE PARK: развлечения
  TTB (COCHERANGSIT CO., LTD.): кафе
  TTB (KOCHERANGSIT CO., LTD.): кафе
  PARK PLAZA BANGKOK SOI 18: кафе
  2008-MAJOR (ICE)-SUKHUMVI: развлечения
  MCD-00057MAJOR SKV 61 (EK: кафе
  PMT. PROMPTPAY: other
  TTB (COSERANGSIT CO., LTD.): кафе
  TTB (KO SERANG SIT CO., LTD.): кафе
  PARK ROYAL CO., LTD.: кафе
  STARBUCKS COFFEE: кафе
  CAROSE WORLD OF MAGIC FOUNDATION: кафе
  CAROUS WORLD OF MAGIC FOUNDATION: животные
  PTTST.D SIRIWATTANA 2025: бензин + мойка
  CP AXTRA PUBLIC CO., LTD.: продукты
  TUNGNGERN (GORAN FOOD): кафе
  PHAKAWAN CHUKHAOWANG: other
  KRUNGSRI MUANG MEE SHOP (TEMMARIN COCKTAIL): кафе
  MR. CHOKCHAI SUEASUI: other
  MR.MON BANGCHIT: other
  NIRAMOL KILNS: other
  GSB MAHA HENG SHOP: other
  MS. BOONYIAM ENMAG: уборка
  1L2J: продукты
  TRUE ARENA HUAHIN: кружки (музыка, муайтай, тайский, зал)
  HEAD ROCK SKATE: кафе
  PHATRAVADI ME: кафе
  MR.D.I.Y.-BW84-PHHP: дом
  FUJI-BLUPORT HUA HIN: кафе
  MR. PIETRO BOLLATI: кафе
  TONIC AND GINGER: кафе
  TOPS-POWER BUY HUAHIN: продукты
  MR. HANS STEFAN SKEPP: машина
patterns: []
clusters:
  - дом
  - склад
  - машина
  - бензин + мойка
  - обязательные лекарства
  - кружки (музыка, муайтай, тайский, зал)
  - уборка
  - коммуналка
  - телефоны, подписки
  - здоровье
  - кафе
  - продукты
  - такси
  - красота
  - товары для детей
  - товары для дома
  - развлечения
  - животные
  - путешествия
  - MRS. KSENIIA BOBKOVA
  - other
