mappings:
  "Cafe Market": "food"
  "COMPANY LTD": "дом"
  "OIL STATION #12": "бензин + мойка"
patterns:
  - pattern: "/^CAF/i"
    cluster: "кафе/рестораны"
clusters:
  - "food"
  - "дом"
  - "склад"
  - "машина аренда"
  - "бензин + мойка"
  - "обязательные лекарства"
  - "кружки"
  - "уборка"
  - "коммуналка"
  - "телефоны, подписки"
  - "здоровье"
  - "кафе/рестораны"
  - "продукты"
  - "такси"
  - "красота"
  - "товары для детей"
  - "развлечения"
  - "дом животные"
  - "путешествия"
